CREATE TABLE `pitprofile` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NULL DEFAULT NULL,
	`Team` VARCHAR(50) NOT NULL DEFAULT '0',
	`Number` VARCHAR(50) NOT NULL DEFAULT '0',
	`Debut` VARCHAR(50) NULL DEFAULT NULL,
	`Born` VARCHAR(50) NULL DEFAULT NULL,
	`Position` VARCHAR(50) NULL DEFAULT NULL,
	`Body` VARCHAR(50) NULL DEFAULT NULL,
	`Photo` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`No`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
