CREATE TABLE `pitsmelt` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`leftgame` INT(11) NOT NULL DEFAULT '0',
	`w` INT(11) NOT NULL DEFAULT '0',
	`l` INT(11) NOT NULL DEFAULT '0',
	`s` INT(11) NOT NULL DEFAULT '0',
	`h` INT(11) NOT NULL DEFAULT '0',
	`ip` DOUBLE NOT NULL DEFAULT '0',
	`k` INT(11) NOT NULL DEFAULT '0',
	`era` FLOAT NOT NULL DEFAULT '0',
	`qs` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`No`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
