CREATE TABLE `pitstat` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`Control` INT(11) NULL DEFAULT NULL,
	`Power` INT(11) NULL DEFAULT NULL,
	`Physical` INT(11) NULL DEFAULT NULL,
	`Def` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`No`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
