CREATE TABLE `pittotal_record` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`G` INT(11) NULL DEFAULT NULL,
	`W` INT(11) NULL DEFAULT NULL,
	`L` INT(11) NULL DEFAULT NULL,
	`S` INT(11) NULL DEFAULT NULL,
	`HLD` INT(11) NULL DEFAULT NULL,
	`IP` VARCHAR(50) NULL DEFAULT NULL,
	`NP` VARCHAR(50) NULL DEFAULT NULL,
	`H` INT(11) NULL DEFAULT NULL,
	`HR` INT(11) NULL DEFAULT NULL,
	`K` INT(11) NULL DEFAULT NULL,
	`BB` INT(11) NULL DEFAULT NULL,
	`R` INT(11) NULL DEFAULT NULL,
	`ER` INT(11) NULL DEFAULT NULL,
	`ERA` DOUBLE NULL DEFAULT NULL,
	`WHIP` DOUBLE NULL DEFAULT NULL,
	`QS` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`No`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
