CREATE TABLE `smelt` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`leftgame` INT(11) NOT NULL DEFAULT '0',
	`h` INT(11) NOT NULL DEFAULT '0',
	`hr` INT(11) NOT NULL DEFAULT '0',
	`avg` FLOAT NOT NULL DEFAULT '0',
	`rbi` INT(11) NOT NULL DEFAULT '0',
	`sb` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`No`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;
