CREATE TABLE `stat` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`Contact` INT(11) NULL DEFAULT NULL,
	`Power` INT(11) NULL DEFAULT NULL,
	`Speed` INT(11) NULL DEFAULT NULL,
	`Eye` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`No`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;
