CREATE TABLE `total_record` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`G` INT(11) NULL DEFAULT NULL,
	`PA` VARCHAR(50) NULL DEFAULT NULL,
	`AB` INT(11) NULL DEFAULT NULL,
	`H` INT(11) NULL DEFAULT NULL,
	`2B` INT(11) NULL DEFAULT NULL,
	`3B` INT(11) NULL DEFAULT NULL,
	`HR` INT(11) NULL DEFAULT NULL,
	`RBI` INT(11) NULL DEFAULT NULL,
	`R` INT(11) NULL DEFAULT NULL,
	`SB` INT(11) NULL DEFAULT NULL,
	`BB` INT(11) NULL DEFAULT NULL,
	`SO` INT(11) NULL DEFAULT NULL,
	`AVG` DOUBLE NULL DEFAULT NULL,
	`OBA` DOUBLE NULL DEFAULT NULL,
	`SA` DOUBLE NULL DEFAULT NULL,
	`OPS` DOUBLE NULL DEFAULT NULL,
	PRIMARY KEY (`No`)
)
COMMENT='나성범의 통산 기록'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
