# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, db_column='No', null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=50, null=True)),
                ('opponent', models.CharField(blank=True, db_column='Opponent', max_length=50, null=True)),
                ('pa', models.IntegerField(blank=True, db_column='PA', null=True)),
                ('ab', models.IntegerField(blank=True, db_column='AB', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('avg', models.FloatField(blank=True, db_column='AVG', null=True)),
                ('oba', models.FloatField(blank=True, db_column='OBA', null=True)),
                ('sa', models.FloatField(blank=True, db_column='SA', null=True)),
                ('ops', models.FloatField(blank=True, db_column='OPS', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'daily_record',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('number', models.CharField(db_column='Number', max_length=50)),
                ('debut', models.CharField(blank=True, db_column='Debut', max_length=50, null=True)),
                ('born', models.CharField(blank=True, db_column='Born', max_length=50, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=50, null=True)),
                ('body', models.CharField(blank=True, db_column='Body', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='SeasonRecord',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('pa', models.IntegerField(blank=True, db_column='PA', null=True)),
                ('ab', models.IntegerField(blank=True, db_column='AB', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('avg', models.FloatField(blank=True, db_column='AVG', null=True)),
                ('oba', models.FloatField(blank=True, db_column='OBA', null=True)),
                ('sa', models.FloatField(blank=True, db_column='SA', null=True)),
                ('ops', models.FloatField(blank=True, db_column='OPS', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'season_record',
            },
        ),
        migrations.CreateModel(
            name='TotalRecord',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('pa', models.CharField(blank=True, db_column='PA', max_length=50, null=True)),
                ('ab', models.IntegerField(blank=True, db_column='AB', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('avg', models.FloatField(blank=True, db_column='AVG', null=True)),
                ('oba', models.FloatField(blank=True, db_column='OBA', null=True)),
                ('sa', models.FloatField(blank=True, db_column='SA', null=True)),
                ('ops', models.FloatField(blank=True, db_column='OPS', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'total_record',
            },
        ),
    ]
