# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitdailyRecord',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=50, null=True)),
                ('opponent', models.CharField(blank=True, db_column='Opponent', max_length=50, null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('s', models.IntegerField(blank=True, db_column='S', null=True)),
                ('hld', models.IntegerField(blank=True, db_column='HLD', null=True)),
                ('ip', models.IntegerField(blank=True, db_column='IP', null=True)),
                ('np', models.IntegerField(blank=True, db_column='NP', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('k', models.IntegerField(blank=True, db_column='K', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('whip', models.FloatField(blank=True, db_column='WHIP', null=True)),
            ],
            options={
                'db_table': 'pitdaily_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitprofile',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('team', models.CharField(db_column='Team', max_length=50)),
                ('number', models.CharField(db_column='Number', max_length=50)),
                ('debut', models.CharField(blank=True, db_column='Debut', max_length=50, null=True)),
                ('born', models.CharField(blank=True, db_column='Born', max_length=50, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=50, null=True)),
                ('body', models.CharField(blank=True, db_column='Body', max_length=50, null=True)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=500, null=True)),
            ],
            options={
                'db_table': 'pitprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PitseasonRecord',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('s', models.IntegerField(blank=True, db_column='S', null=True)),
                ('hld', models.IntegerField(blank=True, db_column='HLD', null=True)),
                ('ip', models.FloatField(blank=True, db_column='IP', null=True)),
                ('np', models.IntegerField(blank=True, db_column='NP', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('k', models.IntegerField(blank=True, db_column='K', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
                ('whip', models.FloatField(blank=True, db_column='WHIP', null=True)),
                ('qs', models.IntegerField(blank=True, db_column='QS', null=True)),
            ],
            options={
                'db_table': 'pitseason_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitsmelt',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('leftgame', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('s', models.IntegerField()),
                ('h', models.IntegerField()),
                ('ip', models.FloatField()),
                ('k', models.IntegerField()),
                ('era', models.FloatField()),
                ('qs', models.IntegerField()),
            ],
            options={
                'db_table': 'pitsmelt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitstat',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('control', models.IntegerField(blank=True, db_column='Control', null=True)),
                ('power', models.IntegerField(blank=True, db_column='Power', null=True)),
                ('physical', models.IntegerField(blank=True, db_column='Physical', null=True)),
                ('def_field', models.IntegerField(blank=True, db_column='Def', null=True)),
            ],
            options={
                'db_table': 'pitstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PittotalRecord',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('s', models.IntegerField(blank=True, db_column='S', null=True)),
                ('hld', models.IntegerField(blank=True, db_column='HLD', null=True)),
                ('ip', models.FloatField(blank=True, db_column='IP', null=True)),
                ('np', models.IntegerField(blank=True, db_column='NP', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('k', models.IntegerField(blank=True, db_column='K', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
                ('whip', models.FloatField(blank=True, db_column='WHIP', null=True)),
                ('qs', models.IntegerField(blank=True, db_column='QS', null=True)),
            ],
            options={
                'db_table': 'pittotal_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Smelt',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('leftgame', models.IntegerField()),
                ('h', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('avg', models.FloatField()),
                ('rbi', models.IntegerField()),
                ('sb', models.IntegerField()),
            ],
            options={
                'db_table': 'smelt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('contact', models.IntegerField(blank=True, db_column='Contact', null=True)),
                ('power', models.IntegerField(blank=True, db_column='Power', null=True)),
                ('speed', models.IntegerField(blank=True, db_column='Speed', null=True)),
                ('eye', models.IntegerField(blank=True, db_column='Eye', null=True)),
            ],
            options={
                'db_table': 'stat',
                'managed': False,
            },
        ),
    ]
